### PR TITLE
better elevator pitch for Struct

### PR DESCRIPTION
**Pull request by dominictarr**
a line that describes what Struct does, instead of just mentioning the other implementation

### CODE REVIEW

**Comment by dominictarr** [comment]
hmm, should Struct be in the transform section? it doesn't actually store anything it self, it's all stored in whatever subtypes it has.

**Comment by dominictarr** [comment]
idea: everything that can just be expressed as a Computed is a transform.
the other Types are distinguished from Computed transforms because they add mutation methods (put, delete, etc). That means Struct is a computed, not a Type.

**Comment by mmckegg** [comment]
Hmm, `Struct` is a bit of a strange anomaly. It has a `set()` function on it, and so therefore allows mutation. It will set all the nested observables will the key/values specified.

Additionally, if you `set()` with keys that aren't sub-observables and then `get()` later, those extra values are preserved. So from that perspective it **does** store data.

**Comment by mmckegg** [comment]
Going to merge this description though! Might add a little to it.

**Comment by dominictarr** [comment]
@mmckegg I liked it better before I knew that! Anyway, Isn't that what Dict is for?

**Comment by mmckegg** [comment]
@dominictarr I think having the `set` function on Struct is a very useful idea.

**The real question is, whether or not it should be preserving those additional keys.** 

I use this a lot in Loop Drop so that I can deserialize some json into a struct, and then pull it back out again without the unknown fields being removed.

The additional keys aren't visible anywhere except when you get the resolved value of the struct.

**Comment by dominictarr** [comment]
> The additional keys aren't visible anywhere except when you get the resolved value of the struct.

Can you describe how you uses that with the JSON thing.

one thing I want to be able to do is have a large object (lots of keys)
where I update keys one at a time, and then I can create observables that watch a single key efficiently. I havn't figured out how to do that with mutant yet

**Comment by mmckegg** [comment]
> create observables that watch a single key efficiently

You can sort of do this with computed, but only if the computed result is a `value` type (as opposed to `reference` type).

---

I mostly handle this by creating `MutantValue`s upfront and streaming the changes into them. They have very little overhead (compare to standard `{}`) if no one is listening. At least that's the theory.

That's what is going on in patchcore `about.obs` https://github.com/ssbc/patchcore/blob/master/about/obs.js#L108 

(`contact.obs` isn't using this pattern, so is a bit less memory efficient)

**Comment by mmckegg** [comment]
> Can you describe how you uses that with the JSON thing?

I have json files on disk that store the root state of setups, projects, chunks etc. When you load a file, it injects the json into a root struct and then whenever that root struct changes, the file is updated.

**Pull request merged**
